accounts/urls.py
from django.urls import path
app_name = 'accounts'
from django.contrib.auth import views
urlpatterns = [
    path('login/',views.LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True),name='login'),
    path('logout/',views.LogoutView.as_view(template_name='accounts/logout.html',next_page='accounts:login'),name='logout')
]

myblog/urls.py
from django.urls import path
from  myblog import views
app_name = 'myblog'
urlpatterns = [
    path('',views.index,name='index'),
    path('list/',views.list,name='list'),
    path('formset/',views.formset,name='formset'),
   
    path('addetud/', views.addetud, name='addetud'),

    path('addprod/',views.addprod,name='addprod'),
    path('prodlist/',views.prodlist,name='prodlist'),
    path('editprod/<int:pk>/',views.editprod,name='editprod'),
    path('delprod/<int:pk>/', views.delprod, name='delprod'),
    path('formsetadd/', views.formsetadd, name='formsetadd'),
    path('formsetadd1/', views.formsetadd1, name='formsetadd1'),
    
    path('pdf1/', views.render_pdf_view, name='render_pdf_view'),
    
    path('addfact/', views.addfact, name='addfact'),
    path('listfact/', views.listfact, name='listfact'),
    path('editfact/<int:pk>/', views.editfact, name='editfact'),
    path('delfact/<int:pk>/', views.delfact, name='delfact'),
    path('listetud/', views.listetud, name='listetud'),
    
]

project1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls', namespace="myblog")),
    path('accounts/',include('accounts.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


myblog/models.py
from django.db import models

# Create your models here.
class Produit(models.Model):
    name = models.CharField(max_length=50)
    libelle = models.CharField(max_length=45)
    prix = models.IntegerField()
    dateprod = models.DateField(auto_now_add=False, auto_now=False,null=True)

    
    class Meta:
        db_table = 'produits'
    def __str__(self):
        return "Prod : {}, lib: {}".format(self.name,self.libelle)

class Grade(models.Model):
    name = models.CharField(max_length=45)
    
    class Meta:
        db_table = 'grades'
    def __str__(self):
        return self.name
class Unite(models.Model):
    lib_unt = models.CharField(max_length=45)
    
    class Meta:
        db_table = 'unites'
    def __str__(self):
        return self.lib_unt
class Personne(models.Model):
    nom = models.CharField(max_length=45)
    prenom = models.CharField(max_length=45)
    grade=models.ForeignKey(Grade,on_delete=models.CASCADE)
    unite = models.ForeignKey(Unite, on_delete=models.CASCADE, null=True)
    qte = models.IntegerField(null=True)
    annee=models.IntegerField(null=True)
    
    class Meta:
        db_table = 'personnes'
    def __str__(self):
        return self.nom
class Etudient(models.Model):
    name = models.CharField(max_length=45)
    date_entr = models.DateField(auto_now_add=False, auto_now=False)
    photo=models.FileField(upload_to='photos/',null=True)
    
    class Meta:
        db_table = 'etudients'
        
    
    def __str__(self):
        return self.name


class Article(models.Model):
    libelle = models.CharField(max_length=40)
    class Meta:
        db_table = 'articles'
    def __str__(self):
        return self.libelle

class Facture(models.Model):
    reference = models.CharField(max_length=40)
    date_fact=models.DateField(auto_now_add=False,auto_now=False,null=True)
    class Meta:
        db_table = 'factures'
        
    def __str__(self):
        return self.reference


class Operation(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE,null=True)
    qte = models.IntegerField()
    facture = models.ForeignKey(Facture, on_delete=models.CASCADE)

    class Meta:
        db_table = 'operations'
        unique_together = ("facture", "article")

    def __str__(self):
        return self.qte

myblog/forms.py
from django import forms
from myblog.models import Produit,Etudient,Facture,Operation
from django.core.exceptions import ValidationError
from crispy_forms.helper import FormHelper
from django.forms.models import BaseModelFormSet
class EtudeForm(forms.ModelForm):
    date_entr = forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(format='%d/%m/%Y')
    )

    class Meta:
        model = Etudient
        fields = '__all__'


class ProduitForm(forms.ModelForm):
    dateprod = forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(format='%d/%m/%Y')
    )

    def clean(self):
        cleaned_data = super(ProduitForm, self).clean()
        for (k,v) in cleaned_data.items():
            print(k,v)

    
    class Meta:
        model = Produit
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }
        error_messages = {
            'libelle': {
                'required': "libelle obligatoire",
            },
            'prix': {
                'required': "prix obligatoire",
            },
        }


    

class FactureForm(forms.ModelForm):
    date_fact=forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(format='%d/%m/%Y')
        )
    class Meta:
        model = Facture
        fields = '__all__'
class OperationForm(forms.ModelForm):
    class Meta:
        model = Operation
        exclude = ['facture']


    def __init__(self, *args, **kwargs):
        super(OperationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
    
        """ def save(self, commit=True):
                instance = super(OperationForm, self).save(commit=False)
                instance.qte=400
                if commit:
                    instance.save()
                return instance
        """   
        """ def clean(self):
            titles = []
            for form in self.formset:
                if self.can_delete and self._should_delete_form(form):
                    continue
                article = form.cleaned_data.get('article')
                if article in titles:
                    raise ValidationError("Articles in a set must have distinct titles.")
                titles.append(article)
    """    

myblog/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.http import HttpResponse
from myblog.models import Unite,Grade,Produit,Facture,Operation,Etudient
from django.db.models import Count, Sum, Case, When
from django.forms import modelformset_factory,inlineformset_factory
from myblog.forms import ProduitForm,EtudeForm,OperationForm,FactureForm

from django.contrib.auth.decorators import login_required
#xhtml2pdf
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa


# Create your views here.
@login_required
def index(request):
    result = Unite.objects.values('lib_unt').filter(personne__annee=2020).annotate(s1=Sum(Case(When(personne__grade=1, then='personne__qte'), default=0)), s2=Sum(Case(When(personne__grade=2, then='personne__qte'), default=0)), s3=Sum(Case(When(personne__grade=3, then='personne__qte'), default=0)))
    test = Unite.objects.all()
    print(test)
    print(result)
    return render(request, 'myblog/index.html', {'results': result})
    
@login_required
def list(request):
    produits = Produit.objects.all()
    ProduitFormset = modelformset_factory(
        Produit, ProduitForm, can_delete=True, extra=0)
    formset = ProduitFormset(request.POST or None,
                             prefix="produits", queryset=produits)
    if request.method == 'POST':
        formset = ProduitFormset(
            request.POST, request.FILES, prefix="produits")
        #return HttpResponse(formset)
        if formset.is_valid():
            #return HttpResponse(formset)
            chaine = formset.data['recordelete'].split(',')
            for i in chaine:
                if formset.data['recordelete']:
                    get_object_or_404(Produit,id=i).delete()
                #if form.data['test']:
                #get_object_or_404(Mouvement,id=form.data['test']).delete()
                             
            for mvt in formset:
                mvt.save()
            return redirect('myblog:index')
    return render(request, "myblog/listprod.html", {"formset": formset})

@login_required
def formset(request):
    produits = Produit.objects.none()
    ProduitFormset = modelformset_factory(
        Produit, ProduitForm, can_delete=True)
    formset = ProduitFormset(request.POST or None,prefix="mouvemens", queryset=produits)
    if request.method == 'POST':
        #return HttpResponse(formset)
        if formset.is_valid():
            instances = formset.save()
            return redirect('myblog:list')
    return render(request, "myblog/formset.html", {"formset": formset})

@login_required
def addprod(request):
    form = ProduitForm(request.POST or None)
    if form.is_valid():
        #return HttpResponse(form.cleaned_data)
        form.save()
        return redirect('myblog:pordlist')
    return render(request,'myblog/addprod.html',{'form':form})


@login_required
def prodlist(request):
    produits = Produit.objects.all()
    return render(request,'myblog/prodlist.html',{'produits':produits})

@login_required
def editprod(request,pk):
    produit = get_object_or_404(Produit, pk=pk)
    form = ProduitForm(request.POST or None, instance=produit)
    if form.is_valid():
        form.save()
        return redirect('myblog:prodlist')
    return render(request,'myblog/editprod.html',{'form':form})

@login_required
def delprod(request,pk):
    produit = get_object_or_404(Produit, pk=pk)
    produit.delete()
    return redirect('myblog:prodlist')

@login_required
def formsetadd(request):
    Formsetproduit = modelformset_factory(
        Produit, ProduitForm, can_delete=True, extra=0)
    formset = Formsetproduit(request.POST or None, request.FILES or None, prefix="produits")
    if request.POST:
        pass
    if formset.is_valid():
        #return HttpResponse(formset)
        instances = formset.save()
        return redirect('myblog:prodlist')
    return render(request,'myblog/formsetadd.html',{'formset':formset})

@login_required
def formsetadd1(request):
    Formsetproduit = modelformset_factory(
    Produit, ProduitForm, can_delete=True, extra=0)
    formset = Formsetproduit(request.POST or None, request.FILES or None, prefix="produits")
    if request.POST:
        pass
    if formset.is_valid():
        instances = formset.save()
        return redirect('myblog:prodlist')
    return render(request,'myblog/formsetadd1.html',{'formset':formset})

@login_required
def render_pdf_view(request):
    template_path = 'myblog/pdf1.html'
    produits= Produit.objects.all()
    context = {'produits': produits}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


@login_required
def addetud(request):
    form = EtudeForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        #return HttpResponse(form.cleaned_data)
        form.save()
        return redirect('myblog:prodlist')
    return render(request, 'myblog/addetud.html', {'form': form})

@login_required
def listetud(request):
    etudients=Etudient.objects.all()
    return render(request, 'myblog/listetud.html', {'etudients': etudients})

@login_required
def addfact(request):
    form = FactureForm(request.POST or None)
    #OperationFormSet = modelformset_factory(Operation, OperationForm, extra=1)
    OperationFormSet = inlineformset_factory(Facture,Operation, OperationForm, extra=1)
    formset = OperationFormSet(
        request.POST or None,  queryset=Operation.objects.none(), prefix='oper')
    """     formset = OperationFormSet(
            request.POST or None, request.FILES or None, queryset=Operation.objects.none(), prefix='oper')
    """    
    if request.method=='POST':
        pass
    if form.is_valid and formset.is_valid():
        fs=form.save(commit=False)
        fs.save()
        instances=formset.save(commit=False)
        for instance in instances:
            instance.facture = fs
            instance.save()

        return redirect('myblog:listfact')
    context={'form':form,'formset':formset}
    return render(request,'myblog/addfact.html',context)

@login_required
def editfact(request,pk):
    fact=get_object_or_404(Facture,pk=pk)
    form=FactureForm(request.POST or None,instance=fact)
    OperationFormsSet=inlineformset_factory(Facture,Operation,OperationForm,extra=1,can_delete=True)
    formset = OperationFormsSet(
        request.POST or None,  instance=fact, prefix='oper')
    if form.is_valid() and formset.is_valid():
        #fs= form.save(commit=False)
        #fs.save()
        form.save()
        instances = formset.save()
        return redirect('myblog:listfact')

    context={'form':form,'formset':formset}
    return render(request,'myblog/editfact.html',context)
 
@login_required
def listfact(request):
    factures=Facture.objects.all()
    return render(request,'myblog/listfact.html',{'factures':factures})

@login_required
def delfact(request,pk):
    facture = get_object_or_404(Facture, pk=pk)
    facture.delete()
    return redirect('myblog:listfact')



myblog/templates/myblog/addetud.html
{% extends 'myblog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="container">
        <form method='post' enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{form|crispy}}
            <input type='submit' class ="btn btn-outline-primary" value='save'>
        </form>
        {% if uploaded_file_url %}
            <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
        {% endif %}
    </div>
{% endblock content %}
{% block javascript %}
{% endblock javascript %}




myblog/templates/myblog/addfact.html
{% extends 'myblog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="button" class="btn btn-sm btn-outline-success add-form-row"
        id="{{ formset.prefix }}">New Ecrivain</button>
        <table  class="table form-table table-bordered table-sm">
            <thead class="text-center">
                <tr>
                    <th>quantite</th>
                    <th>article</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
                {% for form_data in formset %}
                    <tr class="item">
                    {{form_data.id}}
                        <td>
                            {{ form_data.qte|as_crispy_field }}
                        </td>
                        <td>
                            {{ form_data.article|as_crispy_field }}
                        </td>
                        <td>
                            
                            <button type="button" class="btn btn-danger btn-sm remove-form-row"
                                    id="{{ formset.prefix }}">
                                
                                Delete
                            </button>
                    
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {{ formset.management_form }}
        <button type="submit">Submit</button>
    </form>
</div> 

{% endblock content %}
{% block javascript %}
  <script src="{% static 'js/formset_dy.js' %}"></script>
{% endblock javascript %}

myblog/templates/myblog/addprod.html



{% extends 'myblog/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form method='post' novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {{ form.name}}
                </div>
                <div class="col-md-6">
                    {{form.libelle}}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{form.prix}}
                </div>
                <div class="col-md-6">
                    {{form.dateprod}}
                </div>
            </div>
            <input type='submit' class ="btn btn-outline-primary" value='save'>
            <i class ='fa fa-pencil-alt'></i>
        </form>
    </div>
{% endblock content %}
{% block javascript %}
{% endblock javascript %}




myblog/templates/myblog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/all.css' %}">
        {% block styles %}
        {% endblock styles %}
    </head>
    <body>
        <h2>page principale</h2>
        {% if request.user.is_authenticated %}
            <p><a href="{% url 'myblog:listfact' %}">Liste Facure</a></p>
            <p><a href="{% url 'myblog:addfact' %}">Facure</a></p>
            <p><a href="{% url 'myblog:addetud' %}">Etudient</a></p>
            <p><a href="{% url 'myblog:formset' %}">FormSet</a></p>
           <p> <a href="{% url 'myblog:list' %}">Voir les produits</a></p>
            <p><a href="{% url 'accounts:logout' %}">Deconnexion</a></p>
        {% else %}
             <a href="{% url 'accounts:login' %}">connexion</a>
        {% endif %}
        {% block content %}
        {% endblock content %}
        <script src="static 'js/bootstrap/bootstrap.js' "></script>
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        {% block javascript %}
        {% endblock javascript %}

    </body>
</html>

myblog/templates/myblog/editfact.html
{% extends 'myblog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="button" class="btn btn-sm btn-outline-success add-form-row"
        id="{{ formset.prefix }}">New Ecrivain</button>
        <table  class="table form-table table-bordered table-sm">
            <thead class="text-center">
                <tr>
                    <th>quantite</th>
                    <th>article</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
                {% for form_data in formset %}
                    <tr class="item">
                    {{form_data.id|as_crispy_field}}
                        <td style="width: 10%">
                            {{ form_data.qte|as_crispy_field }}
                        </td>
                        <td style="width: 20%">
                            {{ form_data.article|as_crispy_field }}
                        </td>
                        <td style="width: 15%">{{form_data.DELETE}}
                            
                            <button type="button" class="btn btn-danger btn-sm remove-form-row"
                                    id="{{ formset.prefix }}">
                                
                                Delete
                            </button>
                    
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {{ formset.management_form }}
        <button type="submit">Save</button>
    </form>
</div> 

{% endblock content %}
{% block javascript %}
  <script src="{% static 'js/formset_dy.js' %}"></script>
{% endblock javascript %}

myblog/templates/myblog/editprod.html
{% extends 'myblog/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form method="post" action="">
            {% csrf_token %}
                        <div class="row">
                    <div class="col-md-6">
                        {{ form.name}}
                    </div>
                    <div class="col-md-6">
                        {{form.libelle}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{form.prix}}
                    </div>
                    <div class="col-md-6">
                        {{form.dateprod}}
                    </div>
                </div>
            <input type="submit" value="save">
        </form>
    </div>
{% endblock content %}
{% block javascript %}{% endblock javascript %}

myblog/templates/myblog/formset - Copie.html
{% extends 'myblog/base.html' %}
{% load static %}
{% block content %}
    <form method="POST">
            {% csrf_token %}
            <button type="button" class="btn btn-sm btn-outline-success add-form-row"
            id="{{ formset.prefix }}">New produit</button>
            <table id= "formset_table" class="table form-table table-bordered table-sm">
                <thead class="text-center">
                    <tr>
                        <th>name</th>
                        <th>libelle</th>
                        <th>prix</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for form_data in formset %}
                        <tr class="item">
                            <td>
                                {{ form_data.name }}
                            </td>
                            <td>
                                {{ form_data.libelle}}
                            </td>
                            <td>
                                {{ form_data.prix}}
                            </td>
                            <td>
                                <button type="button" class="btn btn-danger btn-sm remove-form-row"
                                        id="{{ formset.prefix }}">
                                    
                                    Delete
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {{ formset.management_form }}
            <button type="submit">Submit</button>
        </form>



{% endblock content %}
{% block javascript%}
  <script src="{% static 'js/formset2.js' %}"></script>
{% endblock javascript%}


myblog/templates/myblog/formset.html
{% extends 'myblog/base.html' %}
{% load static %}
{% block content %}
    <form method="POST">
            {% csrf_token %}
            {{ formset.management_form }}
            <button type="button" class="btn btn-sm btn-outline-success add-form-row"
            id="{{ formset.prefix }}">New produit</button>
            <table id= "formset_table" class="table form-table table-bordered table-sm">
                <thead class="text-center">
                    <tr>
                        <th>name</th>
                        <th>libelle</th>
                        <th>prix</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for form_data in formset %}
                        <tr class="item">
                            <td>
                                {{ form_data.name }}
                            </td>
                            <td>
                                {{ form_data.libelle}}
                            </td>
                            <td>
                                {{ form_data.prix}}
                            </td>
                            <td>
                                <button type="button" class="btn btn-danger btn-sm remove-form-row"
                                        id="{{ formset.prefix }}">
                                    
                                    Delete
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="submit">Submit</button>
        </form>



{% endblock content %}
{% block javascript%}
  <script src="{% static 'js/formset2.js' %}"></script>
{% endblock javascript%}


myblog/templates/myblog/formsetadd.html
{% extends 'myblog/base.html' %}
{% load static %}
{% block content %}
    <form method='post'>
        {% csrf_token %}
        <input type="text" name="recordelete" id="recordelete" >
        {{ formset.management_form }}
        <button type="button" class="add-form-row"
            id="{{ formset.prefix }}">New produit</button>
        <table >
            {% for formset in formset %}
                <tr class='item'>
                
                    <td>{{formset.id}}{{formset.name}}</td>
                    <td>{{formset.libelle}}</td>
                    <td>{{formset.prix}}</td>
                    <td>{{formset.dateprod}}</td>
                    <td>{{formset.DELETE}}
                        <button class ="remove-form-row"
                            id="{{ formset.prefix }}">Delete
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </table>        
        <input type="submit" value="Create">
    </form>
{% endblock content %}
{% block javascript %}
  <script src="{% static 'js/formset_dy.js' %}"></script>
{% endblock javascript %}

myblog/templates/myblog/formsetadd1.html
{% extends 'myblog/base.html' %}
{% load static %}
{% block content %}
    <h1>Add a new bird</h1>
    <form id="form-container" method="POST">
        {% csrf_token %}
        {{formset.management_form}}
        {% for form in formset %}
        <div class="bird-form">
        {{form.as_table}}
        </div>
        {% endfor %}
        <button id="add-form" type="button">Add Another Bird</button>
        <button type="submit">Create Birds</button>
    </form>
{% endblock content %}
{% block javascript %}
  <script >
  let birdForm = document.querySelectorAll(".bird-form")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

        let formNum = birdForm.length-1
        addButton.addEventListener('click', addForm)

        function addForm(e){
            e.preventDefault()

            let newForm = birdForm[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`,'g')
            
            formNum++
            
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
            container.insertBefore(newForm, addButton)
            
            totalForms.setAttribute('value', `${formNum+1}`)
        }
  </script>
{% endblock javascript %}

myblog/templates/myblog/index.html
{% extends 'myblog/base.html' %}

{% block content %}
    <div><p>{{ request.user.username}}</p></div>
    <table>
        <thead>
            <tr>
                <th>Unite</th>
                <th>Grade1</th>
                <th>Grade2</th>
                <th>Grade3</th>
            </tr>
        </thead>
        <tbody>
            {% for res in results %}
                <tr>
                    <td>{{ res.lib_unt }}</td>
                    <td>{{ res.s1}}</td>
                    <td>{{ res.s2}}</td>
                    <td>{{ res.s3}}</td>
                </tr>

            {% endfor %}

        </tbody>

    </table>
{% endblock content %}


myblog/templates/myblog/listetud.html
{% extends "myblog/base.html" %}
{% block content %}
    <table>
        <thead>
        </thead>
            <th>name</th>
            <th>date_entr</th>
            <th>photos</th>
        </thead>
        <tbody>
            {% for etudient in etudients %}
                <tr>
                    <td>{{ etudient.name}}</td>
                    <td>{{ etudient.date_entr}}</td>
                    <td>
                        {% if etudient.photo %}
                            <img src="{{etudient.photo.url}}" >
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}
{% block javascript %}{% endblock javascript %}

myblog/templates/myblog/listfact.html
{% extends 'myblog/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <table >
            <thead>
                <th>Reference</th>
                <th>date</th>
                <th>Actions</th>
            </thead>
            <tbody>
                {% for  item in factures %}
                    <tr >
                        <td>{{item.reference}}</td>
                        <td>{{item.date_fact|date:'d/m/Y'}}</td>
                       <td>
                            <a href="{% url 'myblog:editfact' item.id %}">Edidt</a>
                            <a href="{% url 'myblog:delfact' item.id %}">Delete</a>
                       </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}
{% block javascript %}{% endblock javascript %}